#!/bin/bash -e

# Is the docker vault image present?
docker image ls --format '{{json .}}' | jq -s -e '. | map(select(.Repository == "vault" and .Tag == "1.12.6")) | length == 1' > /dev/null \
  || validate fail "the docker \"vault\" image with tag \"1.12.6\" was not pulled"

# Is the docker vault container running?
IMAGE_ID=$(docker image inspect vault:1.12.6 | jq -r '.[0].Id' | cut -d ':' -f 2 | awk '{print substr($0,1,12)}')
docker ps --format '{{json .}}' | jq -s -e --arg image "$IMAGE_ID" '. | map(select(.Image == $image and .Names == "terraform-basics-vault" and .State == "running")) | length == 1' > /dev/null \
  || validate fail "the docker container named \"terraform-basics-vault\" is not running"