FROM ghcr.io/jumppad-labs/vscode:base-v0.3.2

RUN \
  code-server --install-extension hashicorp.terraform && \
  code-server --install-extension jumppad.workspace-config@0.4.0 && \
  code-server --install-extension hashicorp.hcl