#!/bin/bash -e

# Check that the new image is pulled
docker image ls --format '{{json .}}' | jq -s -e '. | map(select(.Repository == "vault" and .Tag == "1.13.2")) | length == 1' > /dev/null \
  || validate fail "the docker 'vault' image with tag '1.13.2' was not pulled"

# Check that the container is updated
IMAGE_ID=$(docker image inspect vault:1.13.2 | jq -r '.[0].Id' | cut -d ':' -f 2 | awk '{print substr($0,1,12)}')
docker ps --format '{{json .}}' | jq -s -e --arg image "$IMAGE_ID" '. | map(select(.Image == $image and .Names == "terraform-basics-vault" and .State == "running")) | length == 1' > /dev/null \
  || validate fail "the docker container named 'terraform-basics-vault' is not running"