name: Run Functional Tests
on:
  push

jobs:
  functional_tests:
    name: Functional Test Docker
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 3
      
      - name: Install Jumppad
        run: |
          curl https://jumppad.dev/install | bash
      
      - name: Run tests
        run: |
          jumppad test --dont-destroy .
      
      - name: Show Logs
        if: failure()
        run: |
          docker ps -a
          docker images
          docker logs docs.docs.jumppad.dev