name: Build Packer Image for GCP
on:
  push

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 3

      - name: Check for changes
        id: check_for_changes
        run: |
          echo "CHANGE_COUNT=$(git diff --name-only  HEAD^ HEAD | grep 'packer' | wc -l)" >> "$GITHUB_OUTPUT"

      - name: Info
        if: steps.check_for_changes.outputs.CHANGE_COUNT != '0'
        run: |
          echo "changes: ${{ steps.check_for_changes.outputs.CHANGE_COUNT }} event: ${{ github.event_name }}"

      - id: auth
        if: steps.check_for_changes.outputs.CHANGE_COUNT != '0'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_TOKEN }}'

      - name: Set up Cloud SDK
        if: steps.check_for_changes.outputs.CHANGE_COUNT != '0'
        uses: google-github-actions/setup-gcloud@v1

      - name: Setup `packer`
        if: steps.check_for_changes.outputs.CHANGE_COUNT != '0'
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Run `packer`
        if: steps.check_for_changes.outputs.CHANGE_COUNT != '0'
        id: build
        run: |
          cd packer
          packer init image.pkr.hcl
          packer validate image.pkr.hcl
          packer build image.pkr.hcl